[[councillor]]
first_name = 'Julie'
last_name = 'Quinn'
country = 'AUS'

[[councillor]]
first_name = 'Emma'
last_name = 'de Lacey'
country = 'NZL'

[[councillor]]
first_name = 'Heidi'
last_name = 'Cusworth'
country = 'USA'

[[councillor]]
first_name = 'Robin'
last_name = 'Gardner'
country = 'AUS'

[[councillor]]
first_name = 'Neil'
last_name = 'Phillips'
country = 'AUS'

[[councillor]]
first_name = 'Rod'
last_name = 'Phillips'
country = 'AUS'

[[councillor]]
first_name = 'David'
last_name = 'Baldwin'
country = 'AUS'

[[councillor]]
first_name = 'Richard'
last_name = 'Robinson'
country = 'AUS'

[[councillor]]
first_name = 'David'
last_name = 'Rowlands'
country = 'AUS'

[[councillor]]
first_name = 'José Nilton Silva'
last_name = 'Vargas'
country = 'BRA'

[[councillor]]
first_name = 'Francis'
last_name = 'Falardeau'
country = 'CAN'

[[councillor]]
first_name = 'Miroslav'
last_name = 'Seidl'
country = 'CZE'

[[councillor]]
first_name = 'Jan'
last_name = 'Tojnar'
country = 'CZE'

[[councillor]]
first_name = 'Roberto'
last_name = 'Pascual'
country = 'ESP'

[[councillor]]
first_name = 'Pep'
last_name = 'Mayolas'
country = 'ESP'

[[councillor]]
first_name = 'Lauri'
last_name = 'Leppik'
country = 'EST'

[[councillor]]
first_name = 'Timmo'
last_name = 'Tammemäe'
country = 'EST'

[[councillor]]
first_name = 'Jari'
last_name = 'Kaaja'
country = 'FIN'

[[councillor]]
first_name = 'Janne'
last_name = 'Snellman'
country = 'FIN'

[[councillor]]
first_name = 'Marko'
last_name = 'Rößler'
country = 'GER'

[[councillor]]
first_name = 'Pavel'
last_name = 'Levitsky'
country = 'ISR'

[[councillor]]
first_name = 'Guntars'
last_name = 'Mankus'
country = 'LAT'

[[councillor]]
first_name = 'Valters'
last_name = 'Kaminskis'
country = 'LAT'

[[councillor]]
first_name = 'Gediminas'
last_name = 'Trimakas'
country = 'LTU'

[[councillor]]
first_name = 'Matt'
last_name = 'Bixley'
country = 'NZL'

[[councillor]]
first_name = 'Tim'
last_name = 'Farrant'
country = 'NZL'

[[councillor]]
first_name = 'Lisa'
last_name = 'De Speville'
country = 'RSA'

[[councillor]]
first_name = 'Ian'
last_name = 'Bratt'
country = 'RSA'

[[councillor]]
first_name = 'Sergey'
last_name = 'Yashchenko'
country = 'RUS'

[[councillor]]
first_name = 'Oleg'
last_name = 'Kalinin'
country = 'RUS'

[[councillor]]
first_name = 'Bengt'
last_name = 'Nilsson'
country = 'SWE'

[[councillor]]
first_name = 'Anton '
last_name = 'Puhovkin'
country = 'UKR'

[[councillor]]
first_name = 'Volodymyr'
last_name = 'Lipka'
country = 'UKR'

[[councillor]]
first_name = 'Bud'
last_name = 'Laird'
country = 'USA'
