name = '6th Australasian Rogaining Championships 2018'
start = 2018-08-25
end = 2018-08-26
location = 'Manumbar, Queensland, Australia'
organizer = 'Queensland Rogaining Association'
level = 'regional-a'
website = 'http://arc2018.qld.rogaining.org.au'
results = 'http://www.qldrogaine.asn.au/qraonline/html/wp/wp-content/uploads/2018/08/2018-ARC-Results-2.pdf'
complete = true
