name = '10th Australasian Championship 2023'
start = 2023-12-16
end = 2023-12-17
location = 'Lake Tekapo, New Zealand'
organizer = 'Wicked Rogaines team, New Zealand Rogaining Association'
level = 'regional-a'
website = 'https://wickedrogaines.nz/australasian-rogaining-championships-2023/'
results = 'https://wickedrogaines.nz/arcresults/#24hr'
complete = true
