name = '2nd Australasian Rogaining Championships 2014'
start = 2014-10-12
end = 2014-10-13
location = 'Castlemaine, Victoria, Australia'
organizer = 'Victorian Rogaining Association'
level = 'regional-a'
website = 'http://www.arc14.com.au/'
results = 'http://vra.rogaine.asn.au/arc14/vra.rogaine.asn.au/index.php?option=com_docman&task=doc_download&gid=282&Itemid=275'
complete = true
