name = '9th Australasian Championship 2023'
start = 2022-10-07
end = 2022-10-08
location = 'Avoca, Victoria, Australia'
organizer = 'Victorian Rogaining team Association'
level = 'regional-a'
website = 'https://rogainevic.org.au/24hr-australasian-rogaining-championship-in-victoria-8th-9th-october-2022/'
results = 'https://rogainevic.org.au/wp-content/uploads/Course-ARC-VRA_htm.pdf'
complete = true
