name = '7th Australasian Rogaining Championships 2019'
start = 2019-10-09
end = 2019-10-10
location = 'St Helens, Tasmania, Australia'
organizer = 'Rogaining Tasmania'
level = 'regional-a'
website = 'https://arc2019.rt.asn.au/'
results = 'https://arc2019.rt.asn.au/results/'
complete = true
