name = '3rd Australasian Rogaining Championships 2015'
start = 2015-10-10
end = 2015-10-11
location = 'Capertee National Park, New South Wales, Australia'
organizer = 'NSW Rogaining Association'
level = 'regional-a'
website = 'http://arc2015.nswrogaining.org/index.php'
complete = true
