name = '5th Australasian Rogaining Championships 2017'
start = 2017-02-11
end = 2017-02-12
location = 'Waikaia, Otago, New Zealand'
organizer = 'New Zealand Rogaining Association'
level = 'regional-a'
website = 'http://www.rogaine.org.nz/arc2017/home.html'
results = 'http://www.rogaine.org.nz/arc2017/AustralasianChamps2017_Results.htm'
complete = true
