name = '4th Australasian Rogaining Championships 2016'
start = 2016-09-17
end = 2016-09-18
location = 'Nannup, Western Australia'
organizer = 'Western Australian Rogaining Association'
level = 'regional-a'
results = 'http://wa.rogaine.asn.au/index.php/results/556-down-south-electronic-results'
complete = true
