name = '11th Australasian Championship 2024'
start = 2024-09-07
end = 2024-09-08
location = 'Mysterious Traveller, Western Australia'
organizer = 'Western Australia Rogaining Association'
level = 'regional-a'
website = 'https://wa.rogaine.asn.au/index.php/events/744-2024-australasian-rogaine-champs'
results = 'https://rogaine-results.com/event/results/2024/australasian-champs/24hr'
complete = true
