name = '8th Australasian Rogaining Championships 2021'
start = 2021-05-29
end = 2021-05-30
location = 'Burra, South Australia'
organizer = 'South Australian Rogaining Association'
level = 'regional-a'
website = 'https://sarogaining.com.au/event/arc2021/'
results = 'http://act.rogaine.asn.au/navlight/SARA/2021%20ARC%20-%20Deceptive%20Lands/html/'
complete = true
