name = '22nd Czech Rogaining Championships 2018'
start = 2018-06-23
end = 2018-06-24
location = 'Roztoky u Křivoklátu, Czech Republic'
organizer = 'Lokomotiva Beroun, Czech Rogaining Association'
level = 'national-c'
website = 'https://rogaining.ob-lbe.cz/'
results = 'https://rogaining.ob-lbe.cz/vysledky.htm'
complete = true
