name = '21st Czech Rogaining Championships 2017'
start = 2017-06-24
end = 2017-06-25
location = 'Šindelová, Czech Republic'
organizer = 'SKOB Ostrov, Czech Rogaining Association'
level = 'national-c'
website = 'https://rogaining2017.cz/?lang=cs'
results = 'https://rogaining2017.cz/?p=222&lang=cs'
complete = true
