name = '28th Czech Rogaining Championships'
start = 2024-06-29
end = 2024-06-30
location = 'Radvanice, Trutnov district, Czech Republic'
organizer = 'OK 99 Hradec Králové, Czech Association of Rogaining'
level = 'national-c'
website = 'https://rog2024.ok99.cz/'
results = 'https://rog2024.ok99.cz/files/24h_f.html'
complete = true
