name = '23rd Czech Rogaining Championships 2019'
start = 2019-06-29
end = 2016-06-30
location = 'Babiny II, Bohemian Central Mountains, Czech Republic'
organizer = 'Krušnohorský rogainingový klub Litvínov'
level = 'national-c'
website = 'https://rogaining-2019.krk-litvinov.cz/en/'
results = 'https://rogaining-2019.krk-litvinov.cz/en/preliminary-results/'
complete = true
