name = '25th Czech Rogaining Championships 2021'
start = 2021-06-26
end = 2021-06-27
location = 'Křižánky, Discrict Žďár nad Sázavou, Czech Republic'
organizer = 'Czech Rogaining Association'
level = 'national-c'
website = 'https://mcr2021.rogaining.cz/'
results = 'https://mcr2021.rogaining.cz/en/results.html'
complete = true
