name = '17th European Rogaining Championships 2021'
start = 2021-09-04
end = 2021-09-05
location = 'Otepää, Estonia'
organizer = 'MTÜ Seiklushunt and Estonian Orienteering Federation (EOF)'
level = 'regional-e'
website = 'https://seiklushunt.ee/erc21/'
results = 'https://seiklushunt.ee/wp-content/uploads/2021/09/web/results.htm'
complete = true
