name = '15th European Rogaining Championships 2018'
start = 2018-08-24
end = 2018-08-25
location = 'Beregomet, Chernivtsi region, Ukraine'
organizer = 'Ukrainian Orienteering Federation (UOF)'
level = 'regional-e'
website = 'http://erc2018.com/en'
results = 'http://erc2018.com/sites/default/files/documents/ERC2018_4.pdf'
complete = true
