name = '20th ERC 2024'
start = 2024-08-17
end = 2024-08-18
location = 'Misso, Estonia'
organizer = 'TA OK Rogain, Estonian Association of Rogaining'
level = 'regional-e'
website = 'https://erc2024.rogain.ee/'
results = 'https://erc2024.rogain.ee/results24/results.htm'
complete = true
