name = '14th European Rogaining Championships 2017'
start = 2017-04-22
end = 2017-04-23
location = 'San Gimignano, Italy'
organizer = 'IK Prato'
level = 'regional-e'
website = 'https://www.facebook.com/European-Rogaining-Championships-2017-Meiting-288778241499292/'
results = 'https://rogaining.com/attachments/article/330/ERC2017%20results%20short.pdf'
complete = true
