name = '19th ERC 2023'
start = 2023-09-09
end = 2023-09-10
location = 'Turku/Pöytyä, Finland'
organizer = 'Turun Metsänkävijät Orienteering Club, Rogaining Finland'
level = 'regional-e'
website = 'https://www.tume.fi/erc2023/'
results = 'https://www.tume.fi/erc2023/results'
complete = true
