name = '13th European Rogaining Championships 2016'
start = 2016-08-27
end = 2016-08-27
location = 'Albi, Aralar range, Spain'
organizer = 'Club Deportivo Navarra, Sección de Orientación GOT, Gipuzkoako Orientazio Taldea, IbeRogaine Spanish association'
level = 'regional-e'
complete = true
