name = 'Finnish Rogaining Championships 2012'
start = 2012-07-28
end = 2012-07-29
location = 'Viitapohja, Tampere, Finland'
organizer = 'Kalke ry, Finland'
level = 'national-f'
website = 'http://retki.rogaining.fi/index.php?page=2012-pirkanmaa-spring&hl=en'
complete = true
