name = 'Finnish Rogaining Championships 2019'
start = 2019-08-24
end = 2019-08-25
location = 'Vaskijärvi area, Southwest Finland'
organizer = 'Ilpoisten Vuorenkävijät ry, Turun Metsänkävijät ry, Finnish Rogaining Association'
level = 'national-f'
website = 'http://sm2019.turkurogaining.fi/'
results = 'http://www.tume.fi/rogaining/sm2019/index.php?p=14'
complete = true
