name = 'Finnish Rogaining Championships 2013'
start = 2013-08-10
end = 2013-08-11
location = 'Sappee, Pirkanmaa, Finland'
organizer = 'Kalke ry, Finland'
level = 'national-f'
website = 'http://retki.rogaining.fi/'
complete = true
