name = 'Finnish Rogaining Championships 2014'
start = 2014-08-09
end = 2014-08-10
location = 'Hailuoto island, Finland'
organizer = 'Kalke ry, Finland'
level = 'national-f'
website = 'http://retki.rogaining.fi/'
results = 'http://retki.rogaining.fi/uploads/2014/results.htm'
complete = true
