name = 'Finnish Rogaining Championships 2023'
start = 2023-05-06
end = 2023-05-07
location = 'Tesjoki school, Loviisan region, Finland'
organizer = 'Extreme Endurance Athletics & Kingsway cycling team, Rogaining Finland'
level = 'national-f'
website = 'https://www.xendurance.fi/en/sm/'
results = 'https://www.xendurance.fi/sm-rogaining-tulokset/'
complete = true
