name = 'Latvian Rogaining Championships 2018'
start = 2018-07-21
end = 2018-07-22
location = 'Sveikulu Camp, Latvia'
organizer = 'LOF, COK Silva'
level = 'national-lv'
website = 'http://www.rogaining.lv'
results = 'https://coksilva.lv/wp-content/uploads/2018/07/rez.24kartes.htm'
complete = true
