name = 'Latvian Rogaining Championships 2012'
start = 2012-07-14
end = 2012-07-15
location = 'Alūksne municipality, Latvia'
organizer = 'Latvian Orienteering Federation'
level = 'national-lv'
website = 'http://rogaining.lv/jaunumi/data/augsuplades/files/LCR%203%20bulletin%202012.pdf'
complete = true

[[links]]
title = 'Original results & splits'
url = 'http://rogaining.lv/jaunumi/data/augsuplades/files/rezultati/2012/web/splits24.htm'

[[links]]
title = 'Map'
url = 'http://rogaining.lv/jaunumi/data/augsuplades/files/Aluksne.jpg'
