name = 'North American Rogaining Championships 2021'
start = 2021-08-14
end = 2021-08-15
location = 'Northstar Resort, Truckee, USA'
organizer = 'Bay Area Orienteering Club and USOF'
level = 'regional-na'
website = 'https://orienteeringusa.org/2021/09/2021-north-american-rogaining-championships/'
results = 'http://baoc.org/wiki/Results/2021/Tahoe_2021_Rogaine'
complete = true
