name = 'North American Rogaining Championships 2019'
start = 2019-09-14
end = 2019-09-15
location = 'Rock Creek Road, Dinkey Creek, California, USA'
organizer = 'Orienteering USA'
level = 'regional-na'
website = 'http://www.navxchallenge.com/schedule-1/2019/9/7/dinkey-creek-nav-x-challenge-series'
results = 'https://docs.google.com/spreadsheets/d/1ZwxFqVW8EJk0C9mM3yjnNyS3Ip9L9iqGxQFdYqRBlyE/edit#gid=0'
complete = true
