name = 'North American Rogaining Championships 2016'
start = 2016-08-27
end = 2016-08-28
location = 'Sierra National Forest near Shaver Lake, California, USA'
organizer = 'Bay Area Orienteering Club'
level = 'regional-na'
website = 'http://www.navxchallenge.com/schedule-1/2016/2/14/shaver-lake-sierra-navx-challenge-series'
results = 'https://docs.google.com/spreadsheets/d/1st2MOjrJe3FldLwyYrAGUdgUhnRuMGL_X1bfhpWm5KI/edit#gid=0'
complete = true
