name = 'New Zealand Rogaining Championships 2016'
start = 2016-02-27
end = 2016-02-28
location = 'El Dorado woolshed, Mt Watkin Rd., Waikouaiti, New Zealand'
organizer = 'New Zealand Rogaining Association'
level = 'national-nz'
website = 'http://www.rogaine.org.nz/nzchamps2016/home.html'
results = 'http://www.rogaine.org.nz/nzchamps2016/nzchamps2016results.htm'
complete = true
