name = '17th Russian Rogaining Championships 2020'
start = 2020-09-12
end = 2020-09-13
location = 'Ekopark, Rjazanskaja oblast, Russia'
organizer = 'Sport Club "АЗЪ" Rjazan'
level = 'national-r'
website = 'https://vk.com/doc433020481_526756533'
results = 'https://rogaining.ru/download/results/rrc_2020_results.xls'
complete = true
