name = 'Russian Rogaining Championships 2018'
start = 2018-07-21
end = 2018-07-22
location = 'Chakasiya, Russia'
organizer = 'Krasnoyarsk Section of the Russian Rogaining Association'
level = 'national-r'
website = 'http://www.kras-rogaining.ru/'
results = 'http://www.kras-rogaining.ru/blizhajshie-meropriyatiya-2/421-15-j-chempionat-rossii-po-rogejnu.html'
complete = true
