name = 'Russian Rogaining Championships 2015'
start = 2015-09-19
end = 2015-09-20
location = 'Krasnoyarsk, Russia'
organizer = 'Krasnoyarskiy Rogaine'
level = 'national-r'
website = 'http://kras-rogaining.ru/'
complete = true
