name = 'Russian Rogaining Championships 2016'
start = 2016-07-02
end = 2016-07-03
location = 'Sosnovo, Leningradskaja oblast, Russia'
organizer = 'St. Petersburg Section of the Russian Rogaining Association'
level = 'national-r'
website = 'http://www.multsport.ru/starts/rus-run-rogaine-2016/'
results = 'http://www.multsport.ru/images/rogRus16/Rezult-24.pdf'
complete = true
