name = 'Ukrainian Rogaining Championships 2019'
start = 2019-05-18
end = 2019-05-19
location = 'Beregomet, Chernivtsi region, Ukraine'
organizer = 'Ukrainian Orienteering Federation (UOF)'
level = 'national-uk'
website = 'http://www.rogaining.org.ua/index.php/68-rogein-2019'
results = 'http://www.rogaining.org.ua/images/stories/389%20SOR24open.xlsx'
complete = true
