name = '2nd World Rogaining Championships 1996'
start = 1996-08-31
end = 1996-09-01
location = 'Mt Singleton, Western Australia, Australia'
organizer = 'Australian Rogaining Association'
level = 'world'
website = 'http://rogaine.asn.au/World-Championships/2nd-World-Rogaining-Championships-Report.html'
results = 'http://wa.rogaine.asn.au/index.php/results/220-everlasting-results'
complete = false
