name = '7th World Rogaining Championships 2006'
start = 2006-10-13
end = 2006-10-14
location = 'Warrumbungle Mts, NSW, Australia'
organizer = 'Australian Rogaining Association'
level = 'world'
results = 'http://rogaining.org/index.php?option=com_content&view=article&id=24:7th-world-rogaining-championships-warrumbungle-mountains-nsw-australia-2006&catid=12&Itemid=193'
complete = false
