name = '13th World Rogaining Championships 2015'
start = 2015-08-22
end = 2015-08-23
location = 'Kiilopää, Lapland, Finland'
organizer = 'Kalke Ry'
level = 'world'
website = 'http://wrc2015.rogaining.fi/'
results = 'http://wrc2015.rogaining.fi/results.html'
complete = true
