name = '9th World Rogaining Championships 2010'
start = 2010-11-20
end = 2010-11-21
location = 'Cheviot, North Canterbury, New Zealand'
organizer = 'NZRA'
level = 'world'
website = 'http://www.rogaine.org.nz/wrc2010/'
results = 'http://www.rogaine.org.nz/wrc2010/results.htm'
media = '<a href="http://www.maxyourmedia.com/radiosport/Radiosport101123_Forne.wma">Radio interview with WRC2010 Champions Chris Forne and Marcel Hagener</a>'
complete = false
