name = '6th World Rogaining Championships 2004'
start = 2004-05-08
end = 2004-05-09
location = 'Tucson, Arizona, USA'
organizer = 'OUSA'
level = 'world'
results = 'http://rogaining.org/index.php?option=com_content&view=article&id=23:6th-world-rogaining-championship-tucson-arizona-2004&catid=12&Itemid=193'
complete = false
