name = '15th World Rogaining Championships 2017'
start = 2017-08-18
end = 2017-08-19
location = 'Razna, Latvia'
organizer = 'Latvian Rogaining Association'
level = 'world'
website = 'http://wrc2017.rogaining.lv/en/'
results = 'http://wrc2017.rogaining.lv/results/'
complete = true
