name = '8th World Rogaining Championships 2008'
start = 2008-09-13
end = 2008-09-14
location = 'Karula National Park, Estonia'
organizer = 'TAOK Rogaining Club'
level = 'world'
website = 'http://8wrc2008.rogain.ee/'
results = 'http://8wrc2008.rogain.ee/results.php'
complete = false
