name = '4th World Rogaining Championships 2000'
start = 2000-01-15
end = 2000-01-16
location = 'Christchurch, North Canterbury, New Zealand'
organizer = 'NZRA'
level = 'world'
results = 'http://rogaining.org/index.php?option=com_content&view=article&id=21:4th-world-rogaining-championship-christchurch-new-zealand-2000&catid=12&Itemid=193'
complete = false
