name = '5th World Rogaining Championships 2002'
start = 2002-07-26
end = 2002-07-27
location = 'Lesna, Czech Republic'
organizer = 'Czech Rogaining Association'
level = 'world'
results = 'http://rogaining.org/index.php?option=com_content&view=article&id=22:5th-world-rogaining-championships&catid=12&Itemid=193'
complete = false
